### ISSUE TITLE
USB opened but no input from RFID reader

### ISSUE THREAD

**Issue by DBombeeck** [PLCnext/HardwareKitExample#2]
I've gone through the XT kit hardware example and am getting pretty far. I've bought the same hardare (RFID reader, Mini PCIE card, USB breakout) as in the example to keep it as simple as possible. 

As of now I have succesfully compiled the C++ code and have the USB opened according to the logs (I did have to change the Product ID and Vendor ID in the rules file and the RFID driver "RFID_DRIVER.cpp"). It all seems fine, except for that the RFID tags are not coming through , not in debug mode in PnE (data arrays) but also not in the log files. 

I have confirmed that it is not the hardware, as I am able to mount and use (read / write) it on Linux, meaning that the XT kit, PCIE board en USB 3.0 breakout work accordingly. 

As for the software, the C++ library containing the program built without errors or problems just as the RFID_driver source code did. The PLCnext Engineer project was also succesfully built and uploaded to the controller. I also made sure to use the same version of the PLCnCLI and the same firmware as in the example. 

See attached the Output.log of the controller as well as the used PnE project. 

[AXC_F_XT_KIT_rfid-reader.zip](https://github.com/PLCnext/HardwareKitExample/files/11079177/AXC_F_XT_KIT_rfid-reader.zip)
[OutputLog_RFIDreader.txt](https://github.com/PLCnext/HardwareKitExample/files/11079181/OutputLog_RFIDreader.txt)

**Comment by OWarneke** [comment]
Hell DBombeeck,

the Linux you successfully tried the Hardware at was that the PLC or a different Device?

My devices behaviour was like a USB Keyboard that had to be interpreted. 
It is possible that your device behaves differently. (Its very likely as it even has another ID)

Please provide the verbose Output of the lspci , lsusb dmesg

Also make sure that the raw input  can be received.
eg. on the /dev/event*  
e.g. via cat or some small python driver.
Once you have that I would proceed embedding it into the PLCnext Runtime.
It is possible that the Device you have has to be handled differently.

Make sure that the plcnext_firmware user has access to that device (it looks like it has access to something, not sure if its the correct place. you also changed the udev settings or how are you setting permissions?)

**Comment by DBombeeck** [comment]
Dear Oliver, 

I've tried the XT-kit in combination with a USB, which worked perfectly. 
I've tested the RFID reader using the Windows 10 Neuftech application, which also worked perfectly. 

![RFIDreader_test](https://user-images.githubusercontent.com/106061097/228212796-e6f6ea64-3e27-4a0b-8aab-701b0ef31f65.png)

The rules file is present in the /udev/rules.d directory and is changed to use my device ID and vendor ID. 

![RulesFile_linux](https://user-images.githubusercontent.com/106061097/228213012-9e92510e-b7f7-4bb9-836f-9ccdb25f8fff.png)

The path "_/dev/event*_" does not exist for me, only "_/dev/input/event*/_" 
This folder and all contents (so input/ dir and the event* entries) are owned by plcnext_firmware:root. 

See attached all the log outputs of lsusb, lspci and dmesg as well as the used rules file. 

[Linux_lsusb_command.txt](https://github.com/PLCnext/HardwareKitExample/files/11088422/Linux_lsusb_command.txt)
[Linux_lsusb_verbose_command.txt](https://github.com/PLCnext/HardwareKitExample/files/11088423/Linux_lsusb_verbose_command.txt)
[Linux_dmesg_command.txt](https://github.com/PLCnext/HardwareKitExample/files/11088424/Linux_dmesg_command.txt)
[Linux_lspci_verbose_command.txt](https://github.com/PLCnext/HardwareKitExample/files/11088425/Linux_lspci_verbose_command.txt)
[27-usbdevices_permissions.zip](https://github.com/PLCnext/HardwareKitExample/files/11088435/27-usbdevices_permissions.zip)

With kind regards,
Damian Bombeeck

**Comment by DBombeeck** [comment]
The RFID reader example is now working. The biggest problem I eventually ran into was the data interpretation.
In the example on github, the following output is used for the data:

- Data divided into chunks of 3 (elements)
- Each chunk starts with the value 1 or 2 (element 0 of the chunk)
- Each chunk has its key value on element 3.

However, the starting situation is not correct and the following rules turned out to apply to my RFID reader:

- Data divided into chunks of 9 (elements)
- Each chunk starts with the value 2 (element 0 of the chunk), the value 1 does not occur.
- Each chunk has its key value on element 4.

Example of my specific data frame:
**_[2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 39, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 39, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 30, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 31, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 30, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 31, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 34, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 35, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 33, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 34, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 40, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0]_**\

For example, [2, 0, 0, 39, 0, 0, 0, 0, 0,​​​​] is one chunk. You see that the chunk consists of 9 elements, starts with the value 2 on element 0 and that on element 4 (index 3, starting at 0) has the value 39, this value is the key value.

I discovered the above using a small python test application (_neuftech_rfid_reader.py_) which was executed on the linux part. This allowed me to view the raw data of the RFID tags, after which it became clear how my data was structured.
The correct RFID tag also came up with this test application, so I concluded that the hardware worked properly and that the software (permissions, handles and kernel itself) were properly configured. With the above data I then started to investigate where in the C++ code the data chunks are processed.

The main place in the C++ code where the data is processed is the _RFID_DRIVER.cpp_ in the function _void RFID_DRIVER::Execute()_. 

![image](https://user-images.githubusercontent.com/106061097/229162525-0e266aee-63bd-4e16-9168-5e7f249c9e40.png)

In this function the index values ​​for the buffer must be changed as above. These index values ​​are determined after the buffer has been completely printed out via the log after scanning an RFID tag. 
In addition to changing the index values, the _BytesRead_ result must also be adjusted to a different number, because our chunks consist of 9 elements instead of 3. In the code, the variable "_res_" (the amount of bytes read) is therefore set equal to 9 in the if-statement. After these operations i.c.w. editing the VID and PID in the _RFID_driver.hpp_  the code worked properly. No changes need to be made in the _RFID_READER_.

![image](https://user-images.githubusercontent.com/106061097/229163036-f69d4765-cb2c-4aad-b116-6fbcc2ae1c6d.png)

**Comment by martinboers** [comment]
Thanks for the update.
If the RFID reader is the same make and model, then perhaps they changed the internals at some stage. I'm not sure how else to explain the difference in behaviour.
I will add a note to the README to point people to this issue.

**Comment by DBombeeck** [comment]
Glad to be able to help! 

I was convinced that I bought the same hardware as you but am doubting myself now. I think I’m going to purchase the neuftech reader directly from the manufacturer and then print out the raw data to compare.
